### ISSUE TITLE
Ability to sort Files in grid

### ISSUE THREAD

**Issue by WebraumZ** [13hakta/FileAttach#1]
It would be great if user could manually sort files in grid in MIGX-like style

**Comment by 13hakta** [comment]
Grid is sortable. Please show me an example or how to reproduce it to see.

**Comment by WebraumZ** [comment]
It's seems to me, that only sorting by column of the grid is possible. I tried to sort grid items manually dragging them over each other, but with no result.  See the gif below

![2015-02-06 20_37_06](https://cloud.githubusercontent.com/assets/1260989/6084279/a383133c-ae40-11e4-8110-9c690a2fcbb5.gif)

**Comment by 13hakta** [comment]
Well, now I see that you mean custom ordering list. I'll think of it.

**Comment by 13hakta** [comment]
In 1.0.2 release object model was extended with "rank" field. It should be used for manual sorted list. It hidden by default and revealed in column list submenu. Reorder of selected rows is made by D&D technics.
