### ISSUE TITLE
Download error with &privateUrl=`1` / latest MODx 2.5.2

### ISSUE THREAD

**Issue by hexcollective** [13hakta/FileAttach#10]
Getting: {"success":false,"message":"Access denied.","total":0,"data":[],"object":{"code":401}} for all user types (anonymous + manager) > when trying to download file on the frontend with snippet call [[!FileAttach? &tpl=`FileAttach_row_tpl` &showSize=`true` &privateUrl=`1`]]

File permissions have been set for anonymous user. Was working well until update to MODx 2.5.2

**Comment by 13hakta** [comment]
Fixed in v1.0.9
