### ISSUE TITLE
Files are not deleted if they are deleted in manager

### ISSUE THREAD

**Issue by Ruslan-Aleev** [13hakta/FileAttach#13]
1) The file still remains in the sources
![1](https://user-images.githubusercontent.com/12523676/44165922-124b3200-a0db-11e8-94ba-ad173645e42e.png)
![2](https://user-images.githubusercontent.com/12523676/44165923-124b3200-a0db-11e8-8919-dcae3b8b173b.png)

2) It's hard to hit the checkbox
![3](https://user-images.githubusercontent.com/12523676/44165924-12e3c880-a0db-11e8-8831-c84de6c0ff11.png)

MODX 2.6.5
Google Chrome 68.0.3440.106

**Comment by 13hakta** [comment]
Hello, Ruslan. Please provide version of installed MODx.

**Comment by Ruslan-Aleev** [comment]
@13hakta Hello! MODX 2.6.5
