### ISSUE TITLE
Filter snippet output by file extension

### ISSUE THREAD

**Issue by Camo30** [13hakta/FileAttach#15]
Would be great to get the ability to filter the output of the snippet by file extension:
``[[FileAttach? &fileExtension=`pdf`]]``

This way you are able to upload multiple different files and to get separate output on different places on the website. E.g. I would like to show a list of PDF files, elsewhere a list of DOC files from the same resource.

**Comment by 13hakta** [comment]
Implemented in 1.0.11pl
