### ISSUE TITLE
Удаление файла

### ISSUE THREAD

**Issue by radist** [13hakta/FileAttach#2]
Добрый день. 

При удалении файла получаю следующую ошибку:

```
Fatal error: Call to a member function initialize() on a non-object in /home/******/core/components/fileattach/model/fileattach/fileitem.class.php on line 41
```

**Comment by 13hakta** [comment]
Какая у вас версия MODx? На моей 2.3 действительно, возникла ошибка при удалении. В следующем коммите будет исправлено. Проверьте, пожалуйста у себя.

**Comment by radist** [comment]
Версия MODX:
MODX Revolution 2.3.3-pl (traditional)

**Comment by 13hakta** [comment]
Проблема сохранилась?

**Comment by radist** [comment]
```
Fatal error: Call to a member function initialize() on a non-object in /home/************/core/components/fileattach/model/fileattach/fileitem.class.php on line 53
```

Да сохранилась

**Comment by radist** [comment]
Собственно проблема в 

```
$mediaSource = $this->xpdo->getOption('fileattach.mediasource', null, 1);
```

В итоге

```
var_dump($mediaSource);
string(0) ""
```

У меня в конфигурации пустота в fileattach.mediasource . 

Почему так?

**Comment by 13hakta** [comment]
Параметр типа "выпадающий список" становится пустым при переводе фокуса на него. Выберите для fileattach.mediasource значение, для работы компонента оно обязательно.

**Comment by radist** [comment]
Я это понял. Вопрос в том почему он после установки был пустой? И как этого избежать в будущем?

**Comment by 13hakta** [comment]
При установке должно было указать на умолчальный источник с номером 1. Настройка задается стандартным способом, потому не должно быть причин для сбоев в <обычных ситуациях>. Проверил установку пакета на стендовом сайте, где этого пакета ранее не было - настройка создалась как и задумано со значением в 1.
