### ISSUE TITLE
Путь к файлам

### ISSUE THREAD

**Issue by radist** [13hakta/FileAttach#3]
Добрый день.

Если в параметре fileattach.files_path указать путь без слеша в конце и использовать fileattach.put_docid то получаются пути вида

```
/assets/brand/spec21
/assets/brand/spec22
```

Вместо ожидаемого 

```
/assets/brand/spec/21
/assets/brand/spec/22
```

Не то что бы баг, но спорное положение дел.

**Comment by 13hakta** [comment]
Да, совершенно верно - слеш в конце нужен. Об этом указано в документации. Спорность в интуитивности подхода, однако такой же подход у заполнения медиа источников и чтобы не создавать диссонанса подход к указанию пути сохранен.
