### ISSUE TITLE
Core Directory

### ISSUE THREAD

**Issue by EkoOne** [13hakta/FileAttach#6]
@13hakta 
For security when I originally installed MODX I renamed the default "core" folder and moved it above the site root. It all works great.

However, after installing FileAttach I noticed that instead of using the new (correct) core path as I originally configured it, FileAttach created another "core" folder in the site root:

> public_html
> 
> > components
> > 
> > > fileattach
> > > 
> > > > elements
> > > > 
> > > > > chunks
> > > > > plugins
> > > > > snippets

I know that I can manually edit the path to the static files for the FA Chunk, Snippet and Plugin but I assume if/when there's a FA update it will be overwritten.

Is there a way to ensure FA automatically detects non-standard core paths in a future version?

**Comment by 13hakta** [comment]
Beginning from 1.0.7 elements wouldn't be static, so core folder can be moved.
