### ISSUE TITLE
Renaming core folder

### ISSUE THREAD

**Issue by EkoOne** [13hakta/FileAttach#7]
I have FA working fine but I noticed when renaming the ‘core’ folder (as part of hardening MODX) that FA will create a new core folder like so _core > components > fileattach..._ even though the _actual_ core folder exists elsewhere, albeit with a different name and location.

I’m assuming FA is hard-coded to use the naming convention.

Can this be fixed?

**Comment by 13hakta** [comment]
Fixed in 1.0.7
