### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by EkoOne** [13hakta/FileAttach#9]
This is a _very_ minor aesthetic issue.

The title (heading) “Attached Files” is positioned noticeably closer to the left and top of the Manager window compared to other (Extra) titles. I used DevTools for comparison but it's the same for every Extra I've looked at so far.

FileAttach
![file-attach](https://cloud.githubusercontent.com/assets/1754223/14397257/f363ff22-fda1-11e5-828b-acf4f3b2fdd0.png)

DevTools
![dev-tools](https://cloud.githubusercontent.com/assets/1754223/14397256/f354220a-fda1-11e5-8680-dd4f2f39278a.png)

**Comment by 13hakta** [comment]
Paddings revised
